version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: template123!
    ports:
      - 3306:3306

networks:
  default:
    name: template-s-network
    external: true
