spring:
  output:
    ansi:
      enabled: always

server:
  name: spring-api-server-async
  port: 8899
  version: 0.0.1
  formatted-version: v0.0.1

logging:
  level:
    com.templates.springapiserverasync: TRACE
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 1MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
