spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/order_master?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: template123!
  flyway:
    url: jdbc:mysql://localhost:3306?useSSL=false&allowPublicKeyRetrieval=true
    schemas: order_master
    user: root
    password: template123!
    out-of-order: true
  output:
    ansi:
      enabled: always

mybatis:
  type-aliases-package: com.templates.springapiserver.**.model
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  name: spring-api-server-template
  port: 9001
  version: 0.0.1
  formatted-version: v0.0.1

logging:
  level:
    com.templates.springapiserver: TRACE
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 1MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
