spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true # for 404 error exception
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/order_master?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: template123!

  flyway: # flyway Configuration - https://flywaydb.org/documentation/configuration/parameters/
    url: jdbc:mysql://localhost:3306?useSSL=false&allowPublicKeyRetrieval=true
    schemas: order_master # 사용할 스키마, 없을 경우, 생성한다.
    user: root
    password: template123!
    out-of-order: true # migration이 순서 상관 없이 실행될 수 있다.

  output:
    ansi:
      enabled: always

mybatis:
  type-aliases-package: com.templates.springapiserver.**.model
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  name: spring-api-server-template
  port: 9001
  version: 0.0.1
  formatted-version: v0.0.1
  error:
    whitelabel:
      enabled: false # true 인 경우에는 /error 로 redirect 됨

logging:
  level:
    com.templates.springapiserver: TRACE
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 3 # 파일 최대 저장 개수
      max-file-size: 1MB # 파일 크기
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log

