CREATE TABLE `ORDER`
(
    `ORDER_NO` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문번호',
    `ORDER_DATE` DATETIME NOT NULL COMMENT '주문일자',
    `CUSTOMER_NO` BIGINT NOT NULL COMMENT '고객NO',
    `ORDER_STATUS` INT(2) NOT NULL COMMENT '주문상태',
    `ORDER_TOTAL` INT(8) NOT NULL COMMENT '주문합계',
    PRIMARY KEY(`ORDER_NO`)
) COMMENT = '주문';
