CREATE TABLE `ORDER`
(
    `ORDER_NO` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문번호',
    `MEMBER_NO` BIGINT NOT NULL COMMENT '고객NO',
    `ORDER_STATUS` VARCHAR(2) NOT NULL COMMENT '주문상태',
    `ORDER_TOTAL` INT NOT NULL COMMENT '주문합계',
    `DELIVERY_FEE` INT NOT NULL COMMENT '배송비',
    `CRT_DATE` DATETIME NOT NULL COMMENT '생성일자',
    PRIMARY KEY(`ORDER_NO`)
) COMMENT = '주문';
